import Testing

@testable import Glob

// from https://github.com/microsoft/vscode/blob/main/src/vs/base/test/common/glob.test.ts

struct VSCodeTests {
	@Test func simple() throws {
		try assertMatches("node_modules", pattern: "node_modules", options: .vscode)
		try assertDoesNotMatch("node_module", pattern: "node_modules", options: .vscode)
		try assertDoesNotMatch("/node_modules", pattern: "node_modules", options: .vscode)
		try assertDoesNotMatch("test/node_modules", pattern: "node_modules", options: .vscode)
		try assertMatches("test.txt", pattern: "test.txt", options: .vscode)
		try assertDoesNotMatch("test?txt", pattern: "test.txt", options: .vscode)
		try assertDoesNotMatch("/text.txt", pattern: "test.txt", options: .vscode)
		try assertDoesNotMatch("test/test.txt", pattern: "test.txt", options: .vscode)
		try assertMatches("test(.txt", pattern: "test(.txt", options: .vscode)
		try assertDoesNotMatch("test?txt", pattern: "test(.txt", options: .vscode)
		try assertMatches("qunit", pattern: "qunit", options: .vscode)
		try assertDoesNotMatch("qunit.css", pattern: "qunit", options: .vscode)
		try assertDoesNotMatch("test/qunit", pattern: "qunit", options: .vscode)
		try assertMatches("/DNXConsoleApp/Program.cs", pattern: "/DNXConsoleApp/**/*.cs", options: .vscode)
		try assertMatches("/DNXConsoleApp/foo/Program.cs", pattern: "/DNXConsoleApp/**/*.cs", options: .vscode)
		withKnownIssue {
			try assertMatches("C:\\DNXConsoleApp\\Program.cs", pattern: "C:/DNXConsoleApp/**/*.cs", options: .vscode)
		}
		withKnownIssue {
			try assertMatches("C:\\DNXConsoleApp\\foo\\Program.cs", pattern: "C:/DNXConsoleApp/**/*.cs", options: .vscode)
		}
		try assertMatches("", pattern: "*", options: .vscode)
	}

	@Test func dotHidden() throws {
		try assertMatches(".git", pattern: ".*", options: .vscode)
		try assertMatches(".hidden.txt", pattern: ".*", options: .vscode)
		try assertDoesNotMatch("git", pattern: ".*", options: .vscode)
		try assertDoesNotMatch("hidden.txt", pattern: ".*", options: .vscode)
		try assertDoesNotMatch("path/.git", pattern: ".*", options: .vscode)
		try assertDoesNotMatch("path/.hidden.txt", pattern: ".*", options: .vscode)
		try assertMatches(".git", pattern: "**/.*", options: .vscode)
		try assertMatches("/.git", pattern: "**/.*", options: .vscode)
		try assertMatches(".hidden.txt", pattern: "**/.*", options: .vscode)
		try assertDoesNotMatch("git", pattern: "**/.*", options: .vscode)
		try assertDoesNotMatch("hidden.txt", pattern: "**/.*", options: .vscode)
		try assertMatches("path/.git", pattern: "**/.*", options: .vscode)
		try assertMatches("path/.hidden.txt", pattern: "**/.*", options: .vscode)
		try assertMatches("/path/.git", pattern: "**/.*", options: .vscode)
		try assertMatches("/path/.hidden.txt", pattern: "**/.*", options: .vscode)
		try assertDoesNotMatch("path/git", pattern: "**/.*", options: .vscode)
		try assertDoesNotMatch("pat.h/hidden.txt", pattern: "**/.*", options: .vscode)
		try assertMatches("._git", pattern: "._*", options: .vscode)
		try assertMatches("._hidden.txt", pattern: "._*", options: .vscode)
		try assertDoesNotMatch("git", pattern: "._*", options: .vscode)
		try assertDoesNotMatch("hidden.txt", pattern: "._*", options: .vscode)
		try assertDoesNotMatch("path/._git", pattern: "._*", options: .vscode)
		try assertDoesNotMatch("path/._hidden.txt", pattern: "._*", options: .vscode)
		try assertMatches("._git", pattern: "**/._*", options: .vscode)
		try assertMatches("._hidden.txt", pattern: "**/._*", options: .vscode)
		try assertDoesNotMatch("git", pattern: "**/._*", options: .vscode)
		try assertDoesNotMatch("hidden._txt", pattern: "**/._*", options: .vscode)
		try assertMatches("path/._git", pattern: "**/._*", options: .vscode)
		try assertMatches("path/._hidden.txt", pattern: "**/._*", options: .vscode)
		try assertMatches("/path/._git", pattern: "**/._*", options: .vscode)
		try assertMatches("/path/._hidden.txt", pattern: "**/._*", options: .vscode)
		try assertDoesNotMatch("path/git", pattern: "**/._*", options: .vscode)
		try assertDoesNotMatch("pat.h/hidden._txt", pattern: "**/._*", options: .vscode)
	}

	@Test func filePattern() throws {
		try assertMatches("foo.js", pattern: "*.js", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "*.js", options: .vscode)
		try assertDoesNotMatch("/node_modules/foo.js", pattern: "*.js", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "*.js", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "*.js", options: .vscode)
		try assertMatches("html.js", pattern: "html.*", options: .vscode)
		try assertMatches("html.txt", pattern: "html.*", options: .vscode)
		try assertDoesNotMatch("htm.txt", pattern: "html.*", options: .vscode)
		try assertMatches("html.js", pattern: "*.*", options: .vscode)
		try assertMatches("html.txt", pattern: "*.*", options: .vscode)
		try assertMatches("htm.txt", pattern: "*.*", options: .vscode)
		withKnownIssue {
			try assertDoesNotMatch("folder/foo.js", pattern: "*.*", options: .vscode)
		}
		withKnownIssue {
			try assertDoesNotMatch("/node_modules/foo.js", pattern: "*.*", options: .vscode)
		}
		try assertMatches("node_modules/test/foo.js", pattern: "node_modules/test/*.js", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "node_modules/test/*.js", options: .vscode)
		try assertDoesNotMatch("/node_module/test/foo.js", pattern: "node_modules/test/*.js", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "node_modules/test/*.js", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "node_modules/test/*.js", options: .vscode)
	}

	@Test func star() throws {
		try assertMatches("node_modules", pattern: "node*modules", options: .vscode)
		try assertMatches("node_super_modules", pattern: "node*modules", options: .vscode)
		try assertDoesNotMatch("node_module", pattern: "node*modules", options: .vscode)
		try assertDoesNotMatch("/node_modules", pattern: "node*modules", options: .vscode)
		try assertDoesNotMatch("test/node_modules", pattern: "node*modules", options: .vscode)
		try assertMatches("html.js", pattern: "*", options: .vscode)
		try assertMatches("html.txt", pattern: "*", options: .vscode)
		try assertMatches("htm.txt", pattern: "*", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "*", options: .vscode)
		try assertDoesNotMatch("/node_modules/foo.js", pattern: "*", options: .vscode)
	}

	@Test func fileFolderMatch() throws {
		try assertMatches("node_modules", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("node_modules/", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("a/node_modules", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("a/node_modules/", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("node_modules/foo", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("foo/node_modules/foo/bar", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/node_modules", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/node_modules/", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/a/node_modules", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/a/node_modules/", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/node_modules/foo", pattern: "**/node_modules/**", options: .vscode)
		try assertMatches("/foo/node_modules/foo/bar", pattern: "**/node_modules/**", options: .vscode)
	}

	@Test func questionmark() throws {
		try assertMatches("node_modules", pattern: "node?modules", options: .vscode)
		try assertDoesNotMatch("node_super_modules", pattern: "node?modules", options: .vscode)
		try assertDoesNotMatch("node_module", pattern: "node?modules", options: .vscode)
		try assertDoesNotMatch("/node_modules", pattern: "node?modules", options: .vscode)
		try assertDoesNotMatch("test/node_modules", pattern: "node?modules", options: .vscode)
		try assertMatches("h", pattern: "?", options: .vscode)
		try assertDoesNotMatch("html.txt", pattern: "?", options: .vscode)
		try assertDoesNotMatch("htm.txt", pattern: "?", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "?", options: .vscode)
		try assertDoesNotMatch("/node_modules/foo.js", pattern: "?", options: .vscode)
	}

	@Test func globstar() throws {
		try assertMatches("foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("folder/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/node_modules/foo.js", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/some.js/test", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\some.js\\test", pattern: "**/*.js", options: .vscode)
		try assertMatches("project.json", pattern: "**/project.json", options: .vscode)
		try assertMatches("/project.json", pattern: "**/project.json", options: .vscode)
		try assertMatches("some/folder/project.json", pattern: "**/project.json", options: .vscode)
		try assertMatches("/some/folder/project.json", pattern: "**/project.json", options: .vscode)
		try assertDoesNotMatch("some/folder/file_project.json", pattern: "**/project.json", options: .vscode)
		try assertDoesNotMatch("some/folder/fileproject.json", pattern: "**/project.json", options: .vscode)
		try assertDoesNotMatch("some/rrproject.json", pattern: "**/project.json", options: .vscode)
		try assertDoesNotMatch("some\\rrproject.json", pattern: "**/project.json", options: .vscode)
		try assertMatches("test", pattern: "test/**", options: .vscode)
		try assertMatches("test/foo", pattern: "test/**", options: .vscode)
		try assertMatches("test/foo/", pattern: "test/**", options: .vscode)
		try assertMatches("test/foo.js", pattern: "test/**", options: .vscode)
		try assertMatches("test/other/foo.js", pattern: "test/**", options: .vscode)
		try assertDoesNotMatch("est/other/foo.js", pattern: "test/**", options: .vscode)
		try assertMatches("/", pattern: "**", options: .vscode)
		try assertMatches("foo.js", pattern: "**", options: .vscode)
		try assertMatches("folder/foo.js", pattern: "**", options: .vscode)
		try assertMatches("folder/foo/", pattern: "**", options: .vscode)
		try assertMatches("/node_modules/foo.js", pattern: "**", options: .vscode)
		try assertMatches("foo.jss", pattern: "**", options: .vscode)
		try assertMatches("some.js/test", pattern: "**", options: .vscode)
		try assertMatches("test/foo.js", pattern: "test/**/*.js", options: .vscode)
		try assertMatches("test/other/foo.js", pattern: "test/**/*.js", options: .vscode)
		try assertMatches("test/other/more/foo.js", pattern: "test/**/*.js", options: .vscode)
		try assertDoesNotMatch("test/foo.ts", pattern: "test/**/*.js", options: .vscode)
		try assertDoesNotMatch("test/other/foo.ts", pattern: "test/**/*.js", options: .vscode)
		try assertDoesNotMatch("test/other/more/foo.ts", pattern: "test/**/*.js", options: .vscode)
		try assertMatches("foo.js", pattern: "**/**/*.js", options: .vscode)
		try assertMatches("/foo.js", pattern: "**/**/*.js", options: .vscode)
		try assertMatches("folder/foo.js", pattern: "**/**/*.js", options: .vscode)
		try assertMatches("/node_modules/foo.js", pattern: "**/**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "**/**/*.js", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "**/**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertMatches("node_modules/foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertMatches("/node_modules/foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertMatches("node_modules/some/folder/foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertMatches("/node_modules/some/folder/foo.js", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertDoesNotMatch("node_modules/some/folder/foo.ts", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "**/node_modules/**/*.js", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "**/node_modules/**/*.js", options: .vscode)
		withKnownIssue {
			try assertMatches("node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/node_modules/more", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some/test/node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some\\test\\node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/some/test/node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("\\some\\test\\node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("C:\\\\some\\test\\node_modules", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("C:\\\\some\\test\\node_modules\\more", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("bower_components/more", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some/test/bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some\\test\\bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/some/test/bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("\\some\\test\\bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("C:\\\\some\\test\\bower_components", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("C:\\\\some\\test\\bower_components\\more", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches(".git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some/test/.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("some\\test\\.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("/some/test/.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("\\some\\test\\.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
			try assertMatches("C:\\\\some\\test\\.git", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		}
		try assertDoesNotMatch("tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("/tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("some/test/tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("some\\test\\tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("/some/test/tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("\\some\\test\\tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertDoesNotMatch("C:\\\\some\\test\\tempting", pattern: "{**/node_modules/**,**/.git/**,**/bower_components/**}", options: .vscode)
		try assertMatches("package.json", pattern: "{**/package.json,**/project.json}", options: .vscode)
		try assertMatches("/package.json", pattern: "{**/package.json,**/project.json}", options: .vscode)
		try assertDoesNotMatch("xpackage.json", pattern: "{**/package.json,**/project.json}", options: .vscode)
		try assertDoesNotMatch("/xpackage.json", pattern: "{**/package.json,**/project.json}", options: .vscode)
	}

	@Test func issue41724() throws {
		try assertMatches("some/foo.js", pattern: "some/**/*.js", options: .vscode)
		try assertMatches("some/folder/foo.js", pattern: "some/**/*.js", options: .vscode)
		try assertDoesNotMatch("something/foo.js", pattern: "some/**/*.js", options: .vscode)
		try assertDoesNotMatch("something/folder/foo.js", pattern: "some/**/*.js", options: .vscode)
		try assertMatches("some/foo.js", pattern: "some/**/*", options: .vscode)
		try assertMatches("some/folder/foo.js", pattern: "some/**/*", options: .vscode)
		try assertDoesNotMatch("something/foo.js", pattern: "some/**/*", options: .vscode)
		try assertDoesNotMatch("something/folder/foo.js", pattern: "some/**/*", options: .vscode)
	}

	@Test func braceExpansion() throws {
		try assertMatches("foo.js", pattern: "*.{html,js}", options: .vscode)
		try assertMatches("foo.html", pattern: "*.{html,js}", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "*.{html,js}", options: .vscode)
		try assertDoesNotMatch("/node_modules/foo.js", pattern: "*.{html,js}", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "*.{html,js}", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "*.{html,js}", options: .vscode)
		try assertMatches("foo.html", pattern: "*.{html}", options: .vscode)
		try assertDoesNotMatch("foo.js", pattern: "*.{html}", options: .vscode)
		try assertDoesNotMatch("folder/foo.js", pattern: "*.{html}", options: .vscode)
		try assertDoesNotMatch("/node_modules/foo.js", pattern: "*.{html}", options: .vscode)
		try assertDoesNotMatch("foo.jss", pattern: "*.{html}", options: .vscode)
		try assertDoesNotMatch("some.js/test", pattern: "*.{html}", options: .vscode)
		try assertMatches("node_modules", pattern: "{node_modules,testing}", options: .vscode)
		try assertMatches("testing", pattern: "{node_modules,testing}", options: .vscode)
		try assertDoesNotMatch("node_module", pattern: "{node_modules,testing}", options: .vscode)
		try assertDoesNotMatch("dtesting", pattern: "{node_modules,testing}", options: .vscode)
		try assertMatches("foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("test/foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("test/bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("other/more/foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("other/more/bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/test/foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/test/bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/other/more/foo", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("/other/more/bar", pattern: "**/{foo,bar}", options: .vscode)
		try assertMatches("foo", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar/", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("foo/test", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar/test", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar/test/", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("foo/other/more", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar/other/more", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("bar/other/more/", pattern: "{foo,bar}/**", options: .vscode)
		try assertMatches("foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("testing/foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("testing\\foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("/testing/foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("\\testing\\foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("C:\\testing\\foo.js", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("testing/foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("testing\\foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("/testing/foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("\\testing\\foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("C:\\testing\\foo.d.ts", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("testing/foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("testing\\foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("/testing/foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.d", pattern: "{**/*.d.ts,**/*.js}", options: .vscode)
		try assertMatches("foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("testing/foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("testing\\foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("/testing/foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("path/simple.jgs", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertDoesNotMatch("/path/simple.jgs", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("\\testing\\foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("C:\\testing\\foo.js", pattern: "{**/*.d.ts,**/*.js,path/simple.jgs}", options: .vscode)
		try assertMatches("foo.5", pattern: "{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertMatches("foo.8", pattern: "{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertDoesNotMatch("bar.5", pattern: "{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertDoesNotMatch("foo.f", pattern: "{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertMatches("foo.js", pattern: "{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertMatches("prefix/foo.5", pattern: "prefix/{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertMatches("prefix/foo.8", pattern: "prefix/{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertDoesNotMatch("prefix/bar.5", pattern: "prefix/{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertDoesNotMatch("prefix/foo.f", pattern: "prefix/{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
		try assertMatches("prefix/foo.js", pattern: "prefix/{**/*.d.ts,**/*.js,foo.[0-9]}", options: .vscode)
	}

	@Test func brackets() throws {
		try assertMatches("foo.5", pattern: "foo.[0-9]", options: .vscode)
		try assertMatches("foo.8", pattern: "foo.[0-9]", options: .vscode)
		try assertDoesNotMatch("bar.5", pattern: "foo.[0-9]", options: .vscode)
		try assertDoesNotMatch("foo.f", pattern: "foo.[0-9]", options: .vscode)
		try assertDoesNotMatch("foo.5", pattern: "foo.[^0-9]", options: .vscode)
		try assertDoesNotMatch("foo.8", pattern: "foo.[^0-9]", options: .vscode)
		try assertDoesNotMatch("bar.5", pattern: "foo.[^0-9]", options: .vscode)
		try assertMatches("foo.f", pattern: "foo.[^0-9]", options: .vscode)
		try assertDoesNotMatch("foo.5", pattern: "foo.[!0-9]", options: .vscode)
		try assertDoesNotMatch("foo.8", pattern: "foo.[!0-9]", options: .vscode)
		try assertDoesNotMatch("bar.5", pattern: "foo.[!0-9]", options: .vscode)
		try assertMatches("foo.f", pattern: "foo.[!0-9]", options: .vscode)
		try assertDoesNotMatch("foo.5", pattern: "foo.[0!^*?]", options: .vscode)
		try assertDoesNotMatch("foo.8", pattern: "foo.[0!^*?]", options: .vscode)
		try assertMatches("foo.0", pattern: "foo.[0!^*?]", options: .vscode)
		try assertMatches("foo.!", pattern: "foo.[0!^*?]", options: .vscode)
		try assertMatches("foo.^", pattern: "foo.[0!^*?]", options: .vscode)
		try assertMatches("foo.*", pattern: "foo.[0!^*?]", options: .vscode)
		try assertMatches("foo.?", pattern: "foo.[0!^*?]", options: .vscode)
		withKnownIssue {
			try assertDoesNotMatch("foo/bar", pattern: "foo[/]bar", options: .vscode)
		}
		try assertMatches("foo.[", pattern: "foo.[[]", options: .vscode)
		withKnownIssue {
			try assertMatches("foo.]", pattern: "foo.[]]", options: .vscode)
			try assertMatches("foo.]", pattern: "foo.[][!]", options: .vscode)
			try assertMatches("foo.[", pattern: "foo.[][!]", options: .vscode)
			try assertMatches("foo.!", pattern: "foo.[][!]", options: .vscode)
			try assertMatches("foo.]", pattern: "foo.[]-]", options: .vscode)
			try assertMatches("foo.-", pattern: "foo.[]-]", options: .vscode)
		}
	}

	@Test func fullPath() throws {
		try assertMatches("testing/this/foo.txt", pattern: "testing/this/foo.txt", options: .vscode)
	}

	@Test func endingPath() throws {
		try assertMatches("some/path/testing/this/foo.txt", pattern: "**/testing/this/foo.txt", options: .vscode)
	}

	@Test func prefixAgnostic() throws {
		try assertMatches("foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("C:\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertMatches("foo.js", pattern: "**/foo.js", options: .vscode)
		try assertMatches("/foo.js", pattern: "**/foo.js", options: .vscode)
		withKnownIssue {
			try assertMatches("\\foo.js", pattern: "**/foo.js", options: .vscode)
		}
		try assertMatches("testing/foo.js", pattern: "**/foo.js", options: .vscode)
		withKnownIssue {
			try assertMatches("testing\\foo.js", pattern: "**/foo.js", options: .vscode)
		}
		try assertMatches("/testing/foo.js", pattern: "**/foo.js", options: .vscode)
		withKnownIssue {
			try assertMatches("\\testing\\foo.js", pattern: "**/foo.js", options: .vscode)
		}
		withKnownIssue {
			try assertMatches("C:\\testing\\foo.js", pattern: "**/foo.js", options: .vscode)
		}
	}

	@Test func cachedProperly() throws {
		try assertMatches("foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("C:\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertMatches("foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("/testing/foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertMatches("C:\\testing\\foo.js", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.ts", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing/foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing\\foo.js.txt", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("/testing.js/foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
		try assertDoesNotMatch("C:\\testing.js\\foo", pattern: "**/*.js", options: .vscode)
	}

	@Test func invalidGlob() throws {
		try assertDoesNotMatch("foo.js", pattern: "**/*(.js", options: .vscode)
	}
}
