name: Tests

on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9.0"
      - uses: irgaly/setup-mint@v1
      - uses: actions/checkout@v4
      - name: Test
        run: set -o pipefail && swift test | mint run --silent xcbeautify --renderer github-actions
