name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ^15.0.1
      - name: Test
        run: swift test

  linux-test:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: swift test
